# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RetroDataset": "00_data.ipynb",
         "RetroEncoder": "01_model.ipynb",
         "RetroFitModel": "01_model.ipynb",
         "get_grouped_params": "01_model.ipynb",
         "RetroFitModelWrapper": "01_model.ipynb"}

modules = ["data.py",
           "model.py"]

doc_url = "https://ncoop57.github.io/retrofit/"

git_url = "https://github.com/ncoop57/retrofit/tree/master/"

def custom_doc_links(name): return None
